containers:
  core:
    image: skiffos/skiff-core-holoiso:latest
    # systemd
    entrypoint: ["/lib/systemd/systemd"]
    env:
      - "container=docker"
    stopSignal: RTMIN+3
    tty: false
    disableInit: true
    workingDirectory: /
    entrypoint: ["/lib/systemd/systemd"]
    mounts:
      - /dev:/dev
      - /etc/hostname:/etc/hostname:ro
      - /lib/modules:/lib/modules:ro
      - /run/udev:/run/udev
      - /mnt:/mnt
      - /mnt/persist/holo:/home
      - /mnt/persist/skiff/core/repos/tmp:/var/tmp
      - /mnt/persist/skiff/core/repos/docker:/var/lib/docker
      - /mnt/persist/skiff/core/repos/flatpak:/var/lib/flatpak
      - /mnt/persist/skiff/core/repos/pacman:/var/cache/pacman
      - /mnt/persist/skiff/core/repos/log:/var/log
    privileged: true
    startAfterCreate: true
    restartPolicy: "always"
    capAdd:
      - ALL
    hostIPC: true
    hostUTS: true
    hostNetwork: true
    securityOpt:
      - seccomp=unconfined
    tmpFs:
      /run: rw,noexec,nosuid,size=65536k
      /run/lock: rw,noexec,nosuid,size=65536k
users:
  core:
    container: core
    containerUser: core
    containerShell:
      - "/bin/bash"
    auth:
      copyRootKeys: true
images:
  skiffos/skiff-core-holoiso:latest:
    # https://github.com/theVakhovskeIsTaken/holoiso
    pull:
      policy: ifnotexists
      registry: quay.io
